apiVersion: v1
kind: Service
metadata:
  name: orders
  labels: { app: orders }
spec:
  type: {{ .Values.service.type }}
  selector: { app: orders }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
